namespace: default
cortxdata:
  name: cortx-data-pod
  image: centos:7
  nodename: node-1
  mountblkinfo: mnt-blk-info.txt
  secretinfo: secret-info.txt
  serviceaccountname: cortx-sa
  s3:
    numinst: 2
    startportnum: 28051
  motr:
    numclientinst: 1
    startportnum: 29000
    numiosinst: 1
  service:
    clusterip:
      name: cortx-data-clusterip-svc
    headless:
      name: cortx-data-headless-svc
    loadbal:
      name: cortx-data-loadbal-svc
  cfgmap:
    mountpath: /etc/cortx/solution
    volmountname: config001
    name: cortx-data-cfgmap
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert-cfgmap
  machineid:
    mountpath: /etc/cortx/solution/node
    volmountname: machine-id-config
    name:  cortx-data-machine-id-cfgmap
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container