cluster:
  name: cortx-cluster
  id: <<.Values.cortx.cluster.id>>
  node_types:
  - name: data_node
    components:
      - name: utils
      - name: motr
        services:
          - io
      - name: hare
    storage:
    <<.Values.cluster.storage_list>>
  - name: server_node
    components:
    - name: utils
    - name: hare
    - name: rgw
  - name: control_node
    components:
    - name: utils
    - name: csm
      services:
      - agent
  - name: ha_node
    components:
    - name: utils
    - name: ha
  - name: client_node
    components:
    - name: utils
    - name: hare
    - name: motr
      services:
        - motr_client
  storage_sets:
  - name: <<.Values.cluster.storage_sets.name>>
    durability:
      sns: <<.Values.cluster.storage_sets.durability.sns>>
      dix: <<.Values.cluster.storage_sets.durability.dix>>
    nodes:
    <<.Values.cluster.storage_sets.nodes>>
